name: CI

on:
  push:
    branches: ["master"]
  workflow_dispatch:
  repository_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - uses: actions/setup-python@v4
        with:
          python-version: '3.11' 
  
      - name: Build
        run: |
          pip3 install poetry==1.5.1
          poetry config virtualenvs.create false
          poetry install
          python3 main.py
          echo "NEW_TAG=$(cat NEW_TAG.txt)" >> $GITHUB_ENV

      - name: Release
        if: hashFiles('NEW_TAG.txt') != ''
        uses: ncipollo/release-action@v1.10.0
        with:
          artifacts: build/*.zip,build/updater.json
          tag: "${{ env.NEW_TAG }}"
          body: https://github.com/frida/frida/releases
